name: calculator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  math_expressions: ^2.7.0
  latext:
    git:
      url: https://github.com/padukadafa/latext.git
      ref: main

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
